import streamlit as st
import json
import os
import random

# 1. Load Data
@st.cache_data
def load_data():
    """Reads the question database from the JSON file generated by extract.py."""
    with open("questions.json", "r", encoding="utf-8") as f:
        return json.load(f)

questions = load_data()

# 2. Initialize Session State
if "q_index" not in st.session_state:
    st.session_state.q_index = 0
    st.session_state.score = 0
    st.session_state.total_attempted = 0  # Core counter for actual submissions
    st.session_state.answered = False
    st.session_state.is_correct = None
    st.session_state.new_q = True

# --- Sidebar: Settings ---
st.sidebar.title("⚙️ Settings")

# Allow users to jump to a specific question number
start_num = st.sidebar.number_input(
    f"Jump to Question (1-{len(questions)}):", 
    min_value=1, 
    max_value=len(questions), 
    value=st.session_state.q_index + 1
)

if st.sidebar.button("Jump Now"):
    st.session_state.q_index = start_num - 1
    st.session_state.answered = False
    st.session_state.new_q = True
    st.rerun()

st.sidebar.divider()

# --- Sidebar: Statistics (Live Updates) ---
st.sidebar.title("📊 Statistics")

# Use the actual submission count as the denominator for accuracy
real_total = st.session_state.total_attempted

if real_total > 0:
    st.sidebar.metric("Correct Answers", f"{st.session_state.score}")
    st.sidebar.metric("Total Attempted", f"{real_total}")
    
    # Calculate accuracy percentage
    accuracy = (st.session_state.score / real_total) * 100
    st.sidebar.write(f"**Accuracy:** {accuracy:.1f}%")
    
    # Progress bar showing current position in the PDF
    progress = (st.session_state.q_index + 1) / len(questions)
    st.sidebar.progress(progress)
    st.sidebar.caption(f"Current Position: {st.session_state.q_index + 1}/{len(questions)}")
else:
    st.sidebar.info("Submit an answer to see stats!")

# 3. Question Logic & Shuffling
if "current_options" not in st.session_state or st.session_state.new_q:
    q = questions[st.session_state.q_index]
    # In the source PDF, the first option is always the correct one
    correct_text = q["options"][0] 
    
    # Shuffle options so the user doesn't just click the first one every time
    opts = q["options"].copy()
    random.shuffle(opts)
    
    st.session_state.current_options = opts
    st.session_state.correct_text = correct_text
    st.session_state.new_q = False

# --- Main UI ---
st.title("🛵 NSW Rider Knowledge Test")

q = questions[st.session_state.q_index]
st.write(f"**Question {st.session_state.q_index + 1} / {len(questions)}**")

# Display question image if it exists
if q.get("image"):
    img_path = os.path.join("quiz_images", q["image"])
    if os.path.exists(img_path):
        st.image(img_path, width=250) 

st.subheader(q["question"])

# --- Answer Area ---
if not st.session_state.answered:
    # Radio buttons for selecting an answer
    selected = st.radio("Select your answer:", st.session_state.current_options, key=f"r_{st.session_state.q_index}")
    
    if st.button("Submit Answer"):
        st.session_state.answered = True
        st.session_state.total_attempted += 1 # Increment only on actual submit
        
        # Check correctness against the stored original correct text
        if selected == st.session_state.correct_text:
            st.session_state.score += 1
            st.session_state.is_correct = True
        else:
            st.session_state.is_correct = False
        st.rerun()

# --- Feedback & Navigation ---
else:
    if st.session_state.is_correct:
        st.success("✅ Correct")
    else:
        st.error("❌ Incorrect")
        st.info(f"The correct answer was: {st.session_state.correct_text}")
    
    # Move to the next question or show final summary
    if st.session_state.q_index < len(questions) - 1:
        if st.button("Next Question"):
            st.session_state.q_index += 1
            st.session_state.answered = False
            st.session_state.new_q = True 
            st.rerun()
    else:
        st.divider()
        st.balloons()
        st.subheader("🏁 Quiz Completed!")
        
        col1, col2 = st.columns(2)
        col1.metric("Final Score", f"{st.session_state.score} / {st.session_state.total_attempted}")
        
        final_accuracy = (st.session_state.score / st.session_state.total_attempted) * 100
        col2.metric("Final Accuracy", f"{final_accuracy:.1f}%")

        if st.button("Restart Quiz"):
            st.session_state.q_index = 0
            st.session_state.score = 0
            st.session_state.total_attempted = 0
            st.session_state.answered = False
            st.session_state.new_q = True
            st.rerun()